.PHONY: Everything.agda build clean

EVERYTHING_PATH=./src/Mugen/Everything.agda

build: Everything.agda
	agda -i=. ${EVERYTHING_PATH}

Everything.agda:
	echo > ${EVERYTHING_PATH}
	echo "-- DO NOT EDIT THIS FILE!" >> ${EVERYTHING_PATH}
	echo "-- THIS FILE IS AUTOMATICALLY GENERATED BY 'make Everything.agda'" >> ${EVERYTHING_PATH}
	echo >> ${EVERYTHING_PATH}
	echo "module Mugen.Everything where" >> ${EVERYTHING_PATH}
	find ./src -name "*.agda" | sed -e 's|^./src/[/]*|import |' -e 's|/|.|g' -e 's/.agda//' -e '/import Mugen.Everything/d' | LC_COLLATE='C' sort >> ${EVERYTHING_PATH}

clean:
	rm -rf ${EVERYTHING_PATH}
